[package]
name = "noters"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.6.3"
js-sys = "0.3.55"
wasm-bindgen = "0.2.78"
