[package]
name = "bin2dec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
sycamore = "0.6.3"
wee_alloc = "0.4.5"