[package]
name = "markrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.7"
wasm-bindgen = "0.2"

[dependencies.pulldown-cmark]
version = "0.9"
default-features = false
